# fly.toml app configuration file generated for remix-tailwind-test on 2023-05-25T11:31:10+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "remix-tailwind-test"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
